media:
  input: assets/media
  output: assets/media
content:
  - name: posts
    label: Posts
    path: _posts
    type: collection
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: layout, type: string, hidden: true, default: post }
      - { name: date, label: Date, type: date, time: true, required: true }
      - { name: categories, label: Categories, type: string, list: true, required: true }
      - { name: published, label: Published, type: boolean, required: true, default: false }
      - { name: mathjax, label: MathJax, type: boolean, required: true, default: false }
      - { name: excerpt, label: Excerpt, type: text, required: true }
      - { name: body, label: Body, type: rich-text, required: true }
    view:
      fields: [ date, title, published, categories, excerpt ]
      primary: date
      sort: [ date, title ]
